### ISSUE TITLE
unwanted zoom on double tap in iOS

### ISSUE THREAD

**Issue by ojeffcott** [AlexLexo/my-legal-helper#3]
double tap zooming needs to be disabled for ios

**Comment by AlexLexo** [comment]
from my current investigations into this problem, it seems that apple have decided to make it not possible for web developers to disable this feature.

Before ios10 it was done via the standard html meta-tag 'user-scaleable=no' which works everywhere except apple.

The only way to do it, that I have found, is essentially to use programming to modify the browser behaviour but it is an armsrace as everytime a solution is found Apple updates block it.

Apple thinks it should be made impossible to do this because of 'Accessibility'.

You can imagine what browser game developers think about this (double-jump? shoot twice?).

I will continue looking for a better solution...

**Comment by AlexLexo** [comment]
done
